---
title: Spartan Funding 
description: Are you spartan? We are a no frills mortgage broker helping families, individuals, and investors make  the purchase of the next home or investment property. 
meta_img:
twitter:
favicon:
url:
gtm:
schema:
  name: 
  type: 
  image: 
  logo:
  phone: 
  email: 
  social:
  location: 
    address: 
    city: 
    state: 
    zip: 
  hours:
    days:
    opens:
    closes:  
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  terms:
    output: true
  pages: 
    output: true  
defaults:
- scope:
    type: 'pages'
  values:
    layout: default
