---
title: Spartan Funding 
description: Are you spartan? We are a no frills mortgage broker helping families, individuals, and investors make  the purchase of the next home or investment property. 
meta_img:
twitter: "@spartanfundingca"
favicon: /img/favicon.png
url: https://spartanfunding.co
gtm: GTM-5G9W6D7
schema:
  name: Spartan Funding
  type: Local Business
  image: 
  logo: img/spartan_fuding_logo-color.png 
  phone: 916-835-6084
  email: etengman11@gmail.com
  social:
  location: 
    address: 80 Blue Ravine Road, Suite 100
    city: Folsom
    state: CA
    zip: 95630
  hours:
    days:
    opens:
    closes:  
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  terms:
    output: true
  pages: 
    output: true  
defaults:
- scope:
    type: 'pages'
  values:
    layout: default
